### ISSUE TITLE
X.509 support for AWS IoT MQTT

### ISSUE THREAD

**Issue by krausfm** [happy-bubbles/presence-firmware#10]
Maybe I'm just not looking in the right spot, but X.509 support would be awesome, so that one can connect to the AWS IoT services.

**Comment by nemik** [comment]
I would like to do this, but the effort needed to add in that support is very high. I can do this if someone pays me for it or sponsors this feature; but not for free, sorry.

The other thing is that AWS IoT charges you per message sent; with a lot of beacons advertising very often, you'd be paying way too much to AWS for this. That's why it's recommended you run an MQTT broker locally and aggregate and analyze data there. Then you can only send what you need to AWS IoT or other remote servers and save yourself a lot of money and data transfers.
