### ISSUE TITLE
Option to disable raw output

### ISSUE THREAD

**Issue by ashmckenzie** [happy-bubbles/presence-firmware#11]
Loving my new HB's but I can no longer monitor the output of a MQTT '#' subscribe because of the sheer amount of raw output.

Is there any way this can be disabled?

Thanks :)

**Comment by nemik** [comment]
Thanks for the feedback, Ash.

At the moment, there's no filtering. The reason for making the device was to send along all the BLE packets it sees.

In my experience, subscribing to '#' on most networks is very noisy. Usually you subscribe to certain topics you're interested in. 

What kind of filtering did you have in mind?

**Comment by ashmckenzie** [comment]
Perhaps I don't fully understand the purpose of the `happy-bubbles/ble/<detector>/raw/??` topic.  

Could you please describe the payload contents?

**Comment by nemik** [comment]
Sure thing, check out https://www.happybubbles.tech/presence/detector and the "MQTT and Message Format" section.

But in a nutshell. the detectors' firmware will send the raw bytes for every packet it sees to that 'raw' topic. This is so that users who like to fine-tune things and use their own hardware or BLE formats can parse it themselves. It's the 'catch-all' for everything BLE advertisement the detector sees.

Otherwise the firmware tries to do its best to suss out if a packet is an iBeacon or Eddystone type. I chose those since iBeacons and Eddystone are the most common types so created dedicated topics for them.

**Comment by nemik** [comment]
Closing the issue, hopefully it's resolved by now.

**Comment by ashmckenzie** [comment]
I'd dearly love to disable raw output as my four HB's are absolutely smashing my MQTT instance..  I looked into compiling the firmware but cannot see any docs on how I might go about this...  please help! :)

**Comment by nemik** [comment]
Ash, all you'd need to do is uncomment this line: https://github.com/happy-bubbles/presence-firmware/blob/master/user/user_main.c#L432 from the firmware and compile a new version and flash it.

Give that a shot and if you get stuck, I'll try to help out. Maybe make a new issue for it in the firmware project so we can keep all the questions about that in one relevant place. 

Best of luck!
