### ISSUE TITLE
Disable LED completely

### ISSUE THREAD

**Issue by DieterKoblenz** [happy-bubbles/presence-firmware#9]
I would like to suggest an enhancement: possibility to disable the status led completely.

I use Happy Bubbles in my bedroom and I don't want to cover them up completely. However, at the moment I have to because the LED is too bright.

**Comment by nemik** [comment]
Thanks for the suggestion, Dieter. I do agree with you on this and will work to adding this feature.
One thing that scares me a bit is people disabling all indications and then thinking the HB device stopped working entirely. So for that reason I would prefer to keep the LED for the configuration orange.

Can you please tell me more about which specific colours or LED actions continue to light up for you and which firmware version you're running?

**Comment by DieterKoblenz** [comment]
Agreed, in configuration mode the LED should be on Always. 

I am running version 12 and I believe (and I'll check later) the red LED is lit up and the green LED flickers when it detects devices.

**Comment by nemik** [comment]
Please upgrade to the newest one and turn off the led indication in the
MQTT settings to see if that fixes it for you.

**Comment by DieterKoblenz** [comment]
I've tried updating to 13 but the version still shows 12 (I've done it via the webinterface and nodemcu flasher) however the blinking stopped. 

LED is now off.

**Comment by nemik** [comment]
I noticed it gets cached sometimes by the browser. If you clear your cache or try to open the config page with another browser or computer, it should reflect the proper version.

**Comment by githubbuh** [comment]
I am using Firefox on osx.  Have tried to update one sensor.  After pressing update the firmware, the spinning wheel never stopped spinning.  Now the Sensor only shows a purple light, will not broadcast SSID, and won't connect as a usb.  On another sensor, after pressing update the firmware, the status shows completed and asks to upgrade with user1.bin.  I press update the firmware button and the message says successfully updated and the instructions update to show that i need to upload user2.bin.  I have cleared browser cache and the sensor still shows version 12.

**Comment by nemik** [comment]
@githubbuh the purple light thing is definitely weird but you said it won't connect over USB anymore? That should never happen because the USB chip is completely separate from everything else. Can you try to upgrade over USB using the instructions here: https://www.happybubbles.tech/presence/docs/firmware/firmware_upgrade/ ?

If it doesn't work, I suggest just being careful about how you handle the device since it is a kit and could short-circuit if you place it on a metal surface or from static electricity. 

For your other sensor, if it asks you to upload user2.bin, that just means that's the file it needs for a future upgrade. You don't have to do it if the other update took, otherwise you'd be repeating it forever. It always tells you which future upgrade file it needs.

Later this or next week, I'll be looking into why the upgraded version doesn't show up right away and trying to make that happen faster. Lots of people have brought up this problem so I want to solve it.

**Comment by liquidox** [comment]
Thought I was going crazy with the firmware version staying on 12 after flashing it 6 times. Might want to note that somewhere or force invalidate the cache.
